name: Run Telegram Bot

on:
  push:
    branches:
      - master  # Hoặc branch mà bạn muốn chạy bot từ đó
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    steps:
    # Bước 1: Kiểm tra mã nguồn
    - name: Checkout code
      uses: actions/checkout@v2

    # Bước 2: Cài đặt Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Sử dụng Node.js version 14 (hoặc một phiên bản khác mà bạn cần)

    # Bước 3: Cài đặt các phụ thuộc
    - name: Install dependencies
      run: npm install

    # Bước 4: Chạy bot Telegram
    - name: Run Telegram bot
      run: nohup node bot.js &
    
    # Bước 5: Kiểm tra logs
    - name: Check logs
      run: tail -f nohup.out
